### ISSUE TITLE
bower install not working correctly

### ISSUE THREAD

**Issue by mpfeil** [sensebox/EASIN-OpenSenseMap#1]
if components are install via bower install leaflet directive is not working

**Comment by chk1** [comment]
Try hardcoding `angular-leaflet-directive` to version 0.7.11 or 0.8.7 (instead of `angular-leaflet` 0.8.x), I had problems with later versions on OpenSenseMap and Campusplan.

**Comment by mpfeil** [comment]
@chk1 thanks. working right now :tada: 
@AlexIsHappy can you checkout last version and check if everything is working like before
