### ISSUE TITLE
Wrong colors in markers

### ISSUE THREAD

**Issue by robarto** [sensebox/EASIN-OpenSenseMap#3]
Red: submitted
Orange: prevalidated
Green: validated

**Comment by AlexIsHappy** [comment]
Done!

Submitted:
![image](https://cloud.githubusercontent.com/assets/9324526/10510612/b6469bbc-733c-11e5-94f8-6775e5527cec.png)

Prevalidated: 
![image](https://cloud.githubusercontent.com/assets/9324526/10510632/cb7d06b0-733c-11e5-801d-5116a43bcfbb.png)

Validated:
![image](https://cloud.githubusercontent.com/assets/9324526/10510644/d31e5da6-733c-11e5-945e-610b501aace7.png)
