### ISSUE TITLE
Hide Pictures & Info from "Submitted" Observations for "normal users"

### ISSUE THREAD

**Issue by robarto** [sensebox/EASIN-OpenSenseMap#4]
Only admins can see ALL pictures and ALL info.
Normal users do not see pics and info from "submitted" observations - only from prevalidated and validated.
So for normal users only the red marker is visible, on click you see something like "this observation was submitted but is not yet validated"...

**Comment by AlexIsHappy** [comment]
Done!

![image](https://cloud.githubusercontent.com/assets/9324526/10511016/22e6bb88-733f-11e5-849f-8a4557e18432.png)

![image](https://cloud.githubusercontent.com/assets/9324526/10511026/2dfe4f0e-733f-11e5-924e-f41ddbc1a401.png)
