### ISSUE TITLE
Admin Edit Form: Status dropdown

### ISSUE THREAD

**Issue by robarto** [sensebox/EASIN-OpenSenseMap#5]
If an admin edits an observation, he can edit the status by changing the text.
This should be a dropdown or radiobutton or something else giving only the three fixed possibilities "submitted" "prevalidated" "validated"

**Comment by AlexIsHappy** [comment]
Done!

![image](https://cloud.githubusercontent.com/assets/9324526/10511228/7cb7bc2e-7340-11e5-8702-828ce1e4f50b.png)

![image](https://cloud.githubusercontent.com/assets/9324526/10511232/84d4868a-7340-11e5-9a3b-eda477853880.png)
